### ISSUE TITLE
字母A的多余锚点？

### ISSUE THREAD

**Issue by liuxd17thu** [SiberiaHusky/Hooskai-Chamfered-Square#2]
![image](https://github.com/user-attachments/assets/4323405a-c718-4e62-a32b-5ea2d6cdbd62)
如图所示，字母A左下角这个位置有三个挤成一团的锚点，转曲后根据选用的描边方法可能会产生破碎
感觉可以删除右侧垂直分布的两个锚点

**Comment by SiberiaHusky** [comment]
绘制时没注意到 X_X，已经把包含“A”字形的字符都修改了，删掉右侧垂直分布的两个锚点在一些软件里可能会有问题，所以没删
